# Generated by Django 4.0.4 on 2022-06-01 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('innotter', '0004_post_is_liked'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='is_liked',
            new_name='liked_by',
        ),
    ]
